apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ssasd22445-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ssasd22445-quarkus 
  name: ssasd22445-quarkus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ssasd22445-quarkus 
