apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ssasd22445-quarkus 
  janus-idp.io/tekton: ssasd22445-quarkus
  backstage.io/kubernetes-id: ssasd22445-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ssasd22445-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  