apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ssasd22445-quarkus-gitops
  description: This is GitOps manifest for ssasd22445-quarkus   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ssasd22445-quarkus
    janus-idp.io/tekton: ssasd22445-quarkus 
    backstage.io/kubernetes-id: ssasd22445-quarkus 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ssasd22445-quarkus
